spring:
  datasource:
    url: jdbc:mysql://localhost:3306/latestpizza?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: D2_ashraf_69847
    password: sunbeam
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
